### ISSUE TITLE
Improper Neutralization of Input During Web Page Generation in Select2

### ISSUE THREAD

**Issue by musamamasood** [glowlogix/wp-frontend-profile#108]
Dependabot requires a package.json to evaluate your JavaScript dependencies. It had expected to find one at the path: /assets/js/select2/package.json.

In Select2 through 4.0.5, as used in Snipe-IT and other products, rich selectlists allow XSS. This affects use cases with Ajax remote data loading when HTML templates are used to display listbox data.

**Comment by hasnain37** [comment]
issue resolved in #121
