### ISSUE TITLE
WordPress 6.2 is imminent! Are your plugins ready?

### ISSUE THREAD

**Issue by musamamasood** [glowlogix/wp-frontend-profile#109]
Hello, Glowlogix!

WordPress 6.2 is scheduled for release on March 28th, 2023. Are your plugins ready?

Highlights of the release:

- Customize settings for any block:
https://make.wordpress.org/core/2023/02/28/custom-settings-wordpress-6-2/
- Ensure settings for blocks appear correctly in the new block settings tabs:
https://make.wordpress.org/core/2023/03/07/introduction-of-block-inspector-tabs/
- Verify third-party blocks appear in the Style Book for customization:
https://make.wordpress.org/core/2023/02/19/style-book-preview-of-blocks-in-global-styles/
- Minimum height dimensions block support:
https://make.wordpress.org/core/2023/03/06/minimum-height-dimensions-block-support/
- Use the latest with the upgrade to React 18 and avoid common pitfalls:
https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/
- Introducing the HTML API:
https://make.wordpress.org/core/2023/03/07/introducing-the-html-api-in-wordpress-6-2/

For a more comprehensive overview of the upcoming changes, check out the WP 6.2 field guide:
https://make.wordpress.org/core/2023/03/09/wordpress-6-2-field-guide/

After you've tested your plugins and you know they're compatible, take one more minute to change the readme "Tested up to" value to 6.2. Users can feel more confident that they won't encounter any problems with your plugin when they update to the latest WordPress version.

Want to know more about plugin readmes? Some great information lives here: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/.

Here are the current "Tested up to" values for each of your plugins:

* https://wordpress.org/plugins/wp-front-end-profile/ (tested up to 6.2)

If your plugins are compatible in their current version, you do not need to release a new version. All you need to do is update the "Tested up to" value to 6.2 in the readme.txt file under your stable tag directory.

Remember that if a plugin is not marked as compatible with one of the three latest major WordPress releases, a warning will be displayed on its WordPress.org plugin page indicating that the plugin may no longer be maintained or supported. That notice will appear even if the plugin is still perfectly compatible with the current version. The trigger for the notice is strictly the "Tested up to" value in the readme.

If you don't want to keep maintaining your plugin, you can close it down by following the instructions on the advanced tab on your plugin page: https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#how-do-i-close-my-plugin

Again, thank you for all you do for the WordPress community, and we hope you will like 6.2 as much as we do.

Here's where you can get the release candidate for all your testing: https://make.wordpress.org/core/handbook/testing/beta-testing/

— WordPress core contributors

**Comment by hasnain37** [comment]
Tested with WordPress 6.3.2
issue resolved in #121
