### ISSUE TITLE
Setup pages by default

### ISSUE THREAD

**Issue by musamamasood** [glowlogix/wp-frontend-profile#11]
We need to setup plugin pages on plugin installation.

**Comment by specialosis** [comment]
Hi, Author is the issue now resolved.
Having a shortcode "e.g.: [profile]" usable would be better than using templates because with shortcodes you can easily define it to whichever page you want.
Thank you for supporting this fantastic plugin.

**Comment by musamamasood** [comment]
@specialosis we created shortcodes instead of templates, issue related to WordPress pages where these shortcode placed on installation. Thank you for your valuable feedback.

**Comment by specialosis** [comment]
Sorry, I have looked everywhere but can't find the shortcode documentation anywhere.
Please can you kindly write all the usable shotcode here in the comment as it would be more helpful

**Comment by musamamasood** [comment]
@specialosis it's under development and it should available in [v1.0.0](https://github.com/glowlogix/wp-frontend-profile/releases/tag/1.0.0). Meanwhile master branch have single shortcode for frontend profile `[wpfep]`.
