### ISSUE TITLE
Error: Please verify your account.

### ISSUE THREAD

**Issue by raffaelecgcolleo** [glowlogix/wp-frontend-profile#114]
I am getting this error when logging in with the frontend page, but able to log in when using the the wordpress log in form.
I have Google reCaptcha enabled with a plugin for the backend log in and using Google reCaptcha with your plugin.
Same key and secret in both.
 
How should I solve this issue?

**Comment by rukhma-glowlogix** [comment]
we have tested from the frontend login page with google captcha. it works fine from our end please check the video(https://www.loom.com/share/c6d8d4ca6b3c4875859d77c6ad41aab5?sid=30809168-b49b-4b0f-866d-474c9e0c96ce).
there will be issue from the other plugin you are using.

**Comment by rukhma-glowlogix** [comment]
we have tested from the frontend login page with google captcha. it works fine from our end please check the video(https://www.loom.com/share/c6d8d4ca6b3c4875859d77c6ad41aab5?sid=30809168-b49b-4b0f-866d-474c9e0c96ce).
there will be issue from the other plugin you are using.
