### ISSUE TITLE
Problems logging out

### ISSUE THREAD

**Issue by Aichacu** [glowlogix/wp-frontend-profile#123]
Hi Glowlogix team,

When your plugin is active on my WordPress installation, using the default WordPress logout link displays a standard WordPress message screen.

"You are attempting to log out of... (webpage name)
Do you really want to log out?"

This only happens when I have your plugin active. How could I fix it so that the user logs out directly?

Thanks for your help.

**Comment by musamamasood** [comment]
@hasnain37 FYI & action.

**Comment by hasnain37** [comment]
Hey @Aichacu 
We have tested the mentioned issue on our end, its work fine. can you please create a short video on error producing. That would be great.

**Comment by hasnain37** [comment]
@Aichacu issue has been resolved.
