### ISSUE TITLE
Clicking "Forgot password" email link results in 'Error: Your password reset link appears to be invalid. Please request a new link below.'

### ISSUE THREAD

**Issue by caspervoogt** [glowlogix/wp-frontend-profile#128]
**Describe the bug**
Clicking "Forgot password" email link results in 'Error: Your password reset link appears to be invalid. Please request a new link below.'

**Steps to Reproduce**
Click the 'forgot password' link. In my case this is at /login/?action=lostpassword (my login page is /login/). Enter email, open email, click confirmation link. 

**Expected behavior**
It should show a password reset field but instead says  'Error: Your password reset link appears to be invalid. Please request a new link below.'

I am using version 1.3.0 of this plugin and WordPress core is fully up to date. PHP 8.1, LAMP stack.

**Comment by umar-glowlogix** [comment]
Issue Resolved in #137
