### ISSUE TITLE
WordPress 6.5.4 is imminent! 

### ISSUE THREAD

**Issue by hasnain37** [glowlogix/wp-frontend-profile#134]
WordPress 6.5 is scheduled for release on March 26, 2024. Are your plugins ready?

Highlights of the release include:

- Introducing the Interactivity API: this new feature provides a standard way for developers to add interactions to the frontend of their blocks.
https://make.wordpress.org/core/2024/03/04/interactivity-api-dev-note/
- Font Library: manage fonts directly in the Editor with a set of APIs to allow developers to control, adapt, and disable its behavior.
https://make.wordpress.org/core/2024/03/14/new-feature-font-library/
- Block Bindings API: populate Block content with external data such as the post metadata or custom PHP logic.
https://make.wordpress.org/core/2024/03/06/new-feature-the-block-bindings-api/
- Plugin Dependencies: the Plugin Dependencies feature plugin has been merged into Core.
https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/
- Introducing the Script Modules API: this new feature brings native JavaScript Module support to 6.5 and provides two modules for use with the WordPress Interactivity API.
https://make.wordpress.org/core/2024/03/04/script-modules-in-6-5/
- I18N Improvements: the Performant Translations feature plugin has been merged into Core.
https://make.wordpress.org/core/2024/02/27/i18n-improvements-6-5-performant-translations/
- AVIF support comes to 6.5:
https://make.wordpress.org/core/2024/02/23/wordpress-6-5-adds-avif-support/
- Updates to the HTML API:
https://make.wordpress.org/core/2024/03/04/updates-to-the-html-api-in-6-5/

Additional Updates / Breaking Changes:

- The minimum version of MySQL has been raised from v5.0 to v5.5.5.
- PHP_CodeSniffer has been updated to v3.8.1.
- PHPMailer has been updated to v6.9.1.
- @wordpress/scripts version 17 has dropped official support for unmaintained Node.js versions. The oldest supported Node.js version is now Node.js 18.

For a more comprehensive overview of all the upcoming changes, check out the WordPress 6.5 Field Guide at https://make.wordpress.org/core/2024/03/15/wordpress-6-5-field-guide/, which will be updated leading up to the release day (March 26).

There have also been a few notable changes to the Plugin Directory recently:

- Introducing Plugin Previews: this new feature allows your plugin to be demoed via the WordPress Playground.
https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/
- New word count limits to sections of the readme.txt (affects only a very small percentage of plugins):
https://meta.trac.wordpress.org/ticket/7477

*How to test and update your plugins*

You can learn about getting the release candidate version for all your testing in this guide: https://make.wordpress.org/core/handbook/testing/beta-testing/.

After you've tested your plugins and know they're compatible, take a moment to change the readme "Tested up to" value to 6.5. Users can feel more confident that they will not encounter any problems with your plugin when they update to the latest WordPress version.

Want to know more about a plugin's readme.txt file? Some great information lives here: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/.

Here are the current "Tested up to" values for each of your plugins:

* https://wordpress.org/plugins/wp-front-end-profile/ (tested up to 6.4.4)

If your plugins are compatible with their current version, you do not need to release a new version. All you need to do is update the "Tested up to" value to 6.5 in the readme.txt file under your stable tag directory.

Note that if a plugin is not marked as compatible with one of the three latest major WordPress releases, a warning will be displayed on its WordPress.org plugin page indicating that the plugin may no longer be maintained or supported. That notice will appear even if the plugin is still perfectly compatible with the current version. The trigger for the notice is strictly the "Tested up to" value in the readme.

If you don't want to keep maintaining your plugin, you can close it down by following the instructions on the advanced tab on your plugin page: https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#how-do-i-close-my-plugin.

For questions and support, you may also want to know about the new plugin support forums guidelines: https://make.wordpress.org/support/2023/10/new-support-guidelines/.

**Comment by umar-glowlogix** [comment]
Issue Resolved in #137
