### ISSUE TITLE
Test and update Plugin with WordPress 6.6

### ISSUE THREAD

**Issue by hasnain37** [glowlogix/wp-frontend-profile#138]
WordPress 6.6 is scheduled for release on July 16, 2024. Are your plugins ready?

Highlights of the release include:

Block Editor: Merges Gutenberg v17.8-18.5, featuring continued iterations of the Interactivity API, Block API, Block Bindings API, and more.
https://make.wordpress.org/core/2024/06/24/miscellaneous-editor-changes-in-wordpress-6-6/
Options API: Changes handling for autoloading of options in order to improve performance by not autoloading large options.
https://make.wordpress.org/core/2024/06/18/options-api-disabling-autoload-for-large-options/
Prepares for React 19 by including integration of the new React JSX transform and deprecating certain features to avoid bugs or unintended behavior.
https://make.wordpress.org/core/2024/06/07/preparation-for-react-19-upgrade/
HTML API: Introduces a new text decoder and a new token map data structure.
https://make.wordpress.org/core/2024/06/24/updates-to-the-html-api-in-6-6/
Drops support for PHP 7.0 and 7.1.
https://make.wordpress.org/core/2024/04/08/dropping-support-for-php-7-1/
For a more comprehensive overview of all the upcoming changes, check out the WordPress 6.6 Field Guide at https://make.wordpress.org/core/2024/06/25/wordpress-6-6-field-guide/, which will continue to be updated leading up to the release day (July 16).

Secure your WordPress.org account

The Plugin Directory has recently had to deal with compromised WordPress.org plugin developer accounts, so now is a good time to urge you to take measures to secure your WordPress.org account. Learn more on how to regularly audit your plugin's committers, enable release confirmations for your plugins, and use secure passwords and 2FA:
https://make.wordpress.org/plugins/2024/06/26/keeping-your-plugin-committer-accounts-secure/

How to test and update your plugins

You can learn about getting the release candidate version for all your testing in this guide: https://make.wordpress.org/core/handbook/testing/beta-testing/.

After you've tested your plugins and know they're compatible, take a moment to change the readme "Tested up to" value to 6.6. Users can feel more confident that they will not encounter any problems with your plugin when they update to the latest WordPress version.

Want to know more about a plugin's readme.txt file? Some great information lives here: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/.

Here are the current "Tested up to" values for each of your plugins:

https://wordpress.org/plugins/wp-front-end-profile/ (tested up to 6.5.5)
If your plugins are compatible with their current version, you do not need to release a new version. All you need to do is update the "Tested up to" value to 6.6 in the readme.txt file under your stable tag directory.

Note that if a plugin is not marked as compatible with one of the three latest major WordPress releases, a warning will be displayed on its WordPress.org plugin page indicating that the plugin may no longer be maintained or supported. That notice will appear even if the plugin is still perfectly compatible with the current version. The trigger for the notice is strictly the "Tested up to" value in the readme.

If you don't want to keep maintaining your plugin, you can close it down by following the instructions on the advanced tab on your plugin page: https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#how-do-i-close-my-plugin.

For questions and support, you may also want to know about the new plugin support forums guidelines: https://make.wordpress.org/support/2023/10/new-support-guidelines/.

**Comment by Glowtayyab** [comment]
Issue resolved in #140
