### ISSUE TITLE
Remove WFP pages on clearing settings

### ISSUE THREAD

**Issue by zain-glowlogix** [glowlogix/wp-frontend-profile#27]
**Describe the bug**
WFP pages are not deleted when settings are cleared.

**Steps to Reproduce**

Visit the WFP tools then click on the Reset Settings. Settings are cleared and getting the message to create WFP pages. Once you create WFP pages new pages will be created but old pages are not deleted.

**Expected behavior**
WFP old pages should delete, after reset settings.

**Comment by zain-78** [comment]
Fixed c335c3948e477c00fdfd6f2e2a60d6fdef4d9b33
