### ISSUE TITLE
Allow administrator bypass of profile edit restriction

### ISSUE THREAD

**Issue by deltafactory** [glowlogix/wp-frontend-profile#49]
**Is your enhancement related to a problem? Please describe.**
As an administrator, it's not possible to view the profile edit page as other users see it.

Also, I believe it's possible to mitigate the security concerns once they're understood.

**Describe the solution you'd like**
1. Add a setting to remove the restriction on administrators.
2. Identify the security concerns that you're aware of. Depending on the specific issues, myself and others may be able to contribute solutions.

**Comment by zain-glowlogix** [comment]
@deltafactory Thanks for reporting this point, Can you please open pull request for this we'll review and merge.

**Comment by deltafactory** [comment]
Yes I can do that.

Did you have specific security issues that might arise from allowing administrators from editing their profiles? For example, if they should not be allowed to change their email address, that could be blocked explicitly.

**Comment by zain-glowlogix** [comment]
Right now the user can change their email address.

**Comment by musamamasood** [comment]
@deltafactory email shouldn't be allowed to change from the frontend. 

Also, this is required for administrator to enable that feature and it should be disabled by default.

**Comment by deltafactory** [comment]
That was an example. What are your concerns that let you to restrict admins from editing on the front end in the first place?

**Comment by musamamasood** [comment]
@deltafactory Thank you for your pull request. 

Please fix styleci issues and disable email change from frontend for the administrator.

**Comment by deltafactory** [comment]
Do you have other concerns that let you restrict admins from editing on the front end in the first place?

**Comment by deltafactory** [comment]
The email field is now removed when the edited user is an admin.

**Comment by musamamasood** [comment]
Thank you. Please create a new pull request in develop branch with all changes.

**Comment by musamamasood** [comment]
Allow administrator bypass of profile edit restriction has been added in v1.2.3
