### ISSUE TITLE
Nonce Security Issue

### ISSUE THREAD

**Issue by JulioPotier** [glowlogix/wp-frontend-profile#52]
This nonce check, good or bad, will do nothing, this is not a stop or go, just a boolean return.
https://github.com/glowlogix/wp-frontend-profile/blob/e3f2689a12a767b51dcd53491562487c1e18fc63/functions/save-fields.php#L231-L233

The test should be:
`if ( ! isset( $_POST['_wpnonce'] ) || ! wp_verify_nonce( $_POST['_wpnonce'] , 'wpfep_nonce_name' ) ) {
    return;
}`

**Comment by zain-glowlogix** [comment]
FIxed

**Comment by JulioPotier** [comment]
Nice, sync it with the repo now, thank you.
