### ISSUE TITLE
Disable input fields

### ISSUE THREAD

**Issue by DAThosting** [glowlogix/wp-frontend-profile#59]
It would be awesome if a input field could be disabled.

**Describe the solution you'd like**
Array extension:
$fields[] = array(
        'id' => 'testid',
        'label' => 'testlabel',
        'desc' => 'test description',
        'type' => 'text',
        'classes' => 'settings-content',
        'disabled' => true
    );

**Comment by musamamasood** [comment]
@mfaizanrasool Let's discuss in the upcoming release.

**Comment by musamamasood** [comment]
Related # https://wordpress.org/support/topic/remove-url-and-description-bio-fields/

**Comment by musamamasood** [comment]
Merge #72
