### ISSUE TITLE
After successful user registration, user get an email  for - username and password info

### ISSUE THREAD

**Issue by shikhergoyal231** [glowlogix/wp-frontend-profile#60]
**Describe your question**

To set your password, visit the following address:

<https://digitallylearn.com/wp-login.php?example\user>

https://digitallylearn.com/registration/

If you have any problems, please contact us at Example@gmail.com.

Adios!

**-----Need to Change This Mail Id,  and content of the mail ----**

**Comment by shikhergoyal231** [comment]
You can register to see the mail.... https://digitallylearn.com/registration/

**Comment by musamamasood** [comment]
Hi @shikhergoyal231, Thank you for your feedback.

**Comment by hasnain37** [comment]
Hi @shikhergoyal231 These changes are custom. You can customized it by changing email template. Thanks.
