### ISSUE TITLE
Newest Version is conflicting with my login and registration page WordPress.

### ISSUE THREAD

**Issue by Lianghere** [glowlogix/wp-frontend-profile#80]
After enabling it. It breaks my original WordPress login and registration page.

**Comment by musamamasood** [comment]
Hi @Lianghere, 

Please click on **System Status** -> **Get system report** -> **Copy for Support**

Copy that information here, thanks

**Comment by abuzar347** [comment]
@musamamasood I have tested the Wp Front-end Profile(1.2.6)  plugin with WordPress 5.9.3. It's working fine.
