### ISSUE TITLE
Warning: Illegal string offset 'id' in wpfepfunctions.php:161

### ISSUE THREAD

**Issue by hamza-glowlogix** [glowlogix/wp-frontend-profile#9]
Issue present on WordPress versions: 4.8, 4.9, 5

**Comment by musamamasood** [comment]
Re: https://wordpress.org/support/topic/php-warning-in-log-2/

**Comment by musamamasood** [comment]
Fixed in [v1.0.0](https://github.com/glowlogix/wp-frontend-profile/releases/tag/v1.0.0)
