### ISSUE TITLE
When shortcode is used in elementor the page cannot be saved

### ISSUE THREAD

**Issue by danloughmiller** [glowlogix/wp-frontend-profile#97]
When adding the [wpfep] to an Elementor page upon saving Elementor reports a 500 internal server error.

**Steps to Reproduce**
1. Create elementor page
2. Add shortcode element with [wpfep]
3. Attempt to save

Following error is logged:
PHP Fatal error: Uncaught Error: Class 'WPFEP_Profile' not found in [{plugins_folder}/wp-front-end-profile/functions/wpfep-functions.php]

**Comment by hasnain37** [comment]
@danloughmiller this issue is resolved.
